# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84
geckolib_version=5.5.2
irons_lib_version=26.1.2-2.2.0

mod_id=irons_artifice
mod_name=Iron's Arms 'n Artifice
mod_license=All Rights Reserved
mod_version=26.1.2-1.1.0
mod_group_id=io.redspace
mod_logo_file=iaa_logo_gunmetal_lowres.png